name = "atomb"
version = "1.0.0"
gleam = ">= 1.9.0"
description = "An Atom feed builder for Gleam"
licences = ["Apache-2.0"]

repository = { type = "github", user = "lpil", repo = "atomb" }
links = [
  { title = "Sponsor", href = "https://github.com/sponsors/lpil" },
]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_time = ">= 1.0.0 and < 2.0.0"
xmb = ">= 1.4.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
